/** This class was generated by GenTest@Mobacar */
package com.arvoia.sampletask.model;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.mockito.runners.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class ErrorResponseTest {

  /**
   * If the class has a default constructor, then you don't need to instantiate it manually.
   * InjectMocks annotation will do it.<br/>
   * Otherwise use the {@link #setupTest()} method for creating the underTest object.
   */
  @InjectMocks
  private ErrorResponse underTest;

  @Before
  public void setupTest() {
    // prepare test
    MockitoAnnotations.initMocks(this);
  }

  @Test
  public void testGetResult() {
    // given
    String value = "test";
    underTest.setResult(value);
    // when
    String actual = underTest.getResult();
    // then
    assertEquals(value, actual);
  }
  
  @Test
  public void testGetErrorInfo()  {
    // given
    ErrorInfo value = Mockito.mock(ErrorInfo.class);
    underTest.setErrorInfo(value);
    // when
    ErrorInfo actual = underTest.getErrorInfo();
    // then
    assertEquals(value, actual);
  }
  
}
