/** This class was generated by GenTest@Mobacar */
package com.arvoia.sampletask.model;

import static org.junit.Assert.assertEquals;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.mockito.runners.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class OfferTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it
	 * manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest
	 * object.
	 */
	@InjectMocks
	private Offer underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetAvailable() {
		// given
		int value = 1;
		underTest.setAvailable(value);
		// when
		int actual = underTest.getAvailable();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetVehicles() {
		// given
		Vehicles value = Mockito.mock(Vehicles.class);
		
		underTest.setVehicles(value);
		// when
		Vehicles actual = underTest.getVehicles();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetTimStamp() {
		// given
		LocalDateTime value = LocalDateTime.now();
		underTest.setTimestamp(value);
		// when
		LocalDateTime actual = underTest.getTimestamp();
		// then
		assertEquals(value, actual);
	}

}
