/** This class was generated by GenTest@Mobacar */
package com.arvoia.sampletask.model;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.runners.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class VehicleTest {

  /**
   * If the class has a default constructor, then you don't need to instantiate it manually.
   * InjectMocks annotation will do it.<br/>
   * Otherwise use the {@link #setupTest()} method for creating the underTest object.
   */
  @InjectMocks
  private Vehicle underTest;

  @Before
  public void setupTest() {
    // prepare test
    MockitoAnnotations.initMocks(this);
  }

  @Test
  public void testGetBrand() {
    // given
    String value = "test";
    underTest.setBrand(value);
    // when
    String actual = underTest.getBrand();
    // then
    assertEquals(value, actual);
  }
  
  @Test
  public void testGetCategory() {
    // given
    String value = "testcategory";
    underTest.setCategory(value);
    // when
    String actual = underTest.getCategory();
    // then
    assertEquals(value, actual);
  }
  
  @SuppressWarnings("deprecation")
  @Test
  public void testGetBasePrice() {
    // given
    double value = 100.01;
    underTest.setBasePrice(value);
    // when
    double actual = underTest.getBasePrice();
    // then
    assertEquals(value, actual, 0);
  }
}
